### ISSUE TITLE
Back-end: Models creation

### ISSUE THREAD

**Issue by nda-silva** [PacSmack/ArtInerary#6]
- Creation of needed models for the database using Sequelize.

**Comment by LindseyKrause** [comment]
-one more table for user pictures 
-things that the user liked

**Comment by LindseyKrause** [comment]
add user slogan area;

**Comment by LindseyKrause** [comment]
update: user photo for later version.  this will only include image uploading. 

Added slogan area called "catchphrase"

**Comment by LindseyKrause** [comment]
Models should be fixed/complete
